In [ ]:
#model performs logistical regression with three normalised factors, max_temp, min_temp and mean_light
#model2 performs logistical regression with two normalised factors: mean_temp and mean_light
#model3 performs logistical regression with two scaled factors: mean_temp and mean_light

In [22]:
# Import Libraries
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score
import numpy as np
import warnings
import pandas as pd
from sklearn.metrics import confusion_matrix, accuracy_score

# Surpress warnings
warnings.filterwarnings("ignore")


In [3]:
#Preprocessing
#generate fake input data for testing
max_temp_raw = [20.1, 17.9, 19, 20.1, 16.1, 19.0]
min_temp_raw = [18.3,16.5,17.6,18.8,14.3,18.6]
mean_light_raw = [3259,3784,3969,3799,3803,3550]

normalised_max_temp = preprocessing.normalize([max_temp_raw])
normalised_min_temp = preprocessing.normalize([min_temp_raw])
normalised_mean_light = preprocessing.normalize([mean_light_raw])
#input data and reshape onto -1 to +1
max_temp = np.array(normalised_max_temp).reshape(-1, 1)
min_temp = np.array(normalised_min_temp).reshape(-1, 1)
mean_light = np.array(normalised_mean_light).reshape(-1, 1)

Y = np.array([0, 0, 1, 1, 0, 0]) #outcomes, 0=poor sleep, 1= good sleep

#normalise data

print('max temp =', max_temp)
print('min temp =', min_temp)
print('mean light =', mean_light)
print('outcomes = ', Y)

max temp = [[0.43761468]
 [0.38971656]
 [0.41366562]
 [0.43761468]
 [0.35052718]
 [0.41366562]]
min temp = [[0.42886555]
 [0.38668205]
 [0.41246086]
 [0.44058319]
 [0.33512444]
 [0.43589613]]
mean light = [[0.35947922]
 [0.41738858]
 [0.43779473]
 [0.41904313]
 [0.41948434]
 [0.39157755]]
outcomes =  [0 0 1 1 0 0]


In [10]:

# Combine factors into feature matrix
X = np.concatenate((max_temp,min_temp,mean_light), axis=1)

# Create and fit the logistic regression model
model = LogisticRegression(solver='liblinear')
model.fit(X, Y)

# Print the coefficients and intercept
print(X)
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

[[0.43761468 0.42886555 0.35947922]
 [0.38971656 0.38668205 0.41738858]
 [0.41366562 0.41246086 0.43779473]
 [0.43761468 0.44058319 0.41904313]
 [0.35052718 0.33512444 0.41948434]
 [0.41366562 0.43589613 0.39157755]]
Coefficients: [[-0.09873949 -0.09567204 -0.09420868]]
Intercept: [-0.33401908]


In [9]:
#Testing accuracy
prediction = model.predict(X)
accuracy = accuracy_score(Y, prediction)
print(prediction)
print(model)
print(accuracy)


[0 0 0 0 0 0]
LogisticRegression(solver='liblinear')
0.6666666666666666


In [39]:
#rerunning with means
mean_temp_raw = [19.18,17.63,18.70,19.22,14.77,18.80]
normalised_mean_temp = preprocessing.normalize([mean_temp_raw])
mean_temp = np.array(normalised_mean_temp).reshape(-1, 1)

print(mean_temp)


[[0.43219902]
 [0.39727157]
 [0.42138277]
 [0.43310037]
 [0.33282479]
 [0.42363616]]


In [34]:
# Combine factors (just means) into feature matrix
X2 = np.concatenate((mean_temp, mean_light), axis=1)
model2 = LogisticRegression(solver='liblinear')
model2.fit(X2, Y)

print(X2)
print("Coefficients:", model2.coef_)
print("Intercept:", model2.intercept_)

[[0.43219902 0.35947922]
 [0.39727157 0.41738858]
 [0.42138277 0.43779473]
 [0.43310037 0.41904313]
 [0.33282479 0.41948434]
 [0.42363616 0.39157755]]
Coefficients: [[-0.10283099 -0.10228296]]
Intercept: [-0.35400767]


In [45]:
#trying with scaling
scaler = StandardScaler()
mean_temp2 = np.array(mean_temp_raw).reshape(-1, 1)
mean_light2 = np.array(mean_light_raw).reshape(-1, 1)
X3 = np.concatenate((mean_temp2, mean_light2), axis=1)
X3_scaled = scaler.fit_transform(X3)
##mean_temp_scaled = 


#model2 = LogisticRegression(solver='liblinear')
print (mean_temp_raw)
print (mean_light_raw)
print (X3)

print(X3_scaled)

[19.18, 17.63, 18.7, 19.22, 14.77, 18.8]
[3259, 3784, 3969, 3799, 3803, 3550]
[[  19.18 3259.  ]
 [  17.63 3784.  ]
 [  18.7  3969.  ]
 [  19.22 3799.  ]
 [  14.77 3803.  ]
 [  18.8  3550.  ]]
[[ 0.72525358 -1.89371629]
 [-0.26956328  0.39180337]
 [ 0.41718126  1.19717696]
 [ 0.75092627  0.45710393]
 [-2.10516082  0.47451741]
 [ 0.48136299 -0.62688539]]


In [48]:
#new logistical regression model just scaling raw data
model3 = LogisticRegression(solver='liblinear')
model3.fit(X3_scaled, Y)

print("Coefficients:", model3.coef_)
print("Intercept:", model3.intercept_)

Coefficients: [[0.65400514 0.83278594]]
Intercept: [-0.44215077]
